import { isResolveFailure, parseId, practiceVariant, questionFromId } from '@80in8/core'
import type { JSX } from 'preact'
import { useEffect, useRef } from 'preact/hooks'
import { profilesReady } from '../adapters/profiles.js'
import { params } from '../adapters/router.js'
import { readProfile } from '../adapters/share.js'
import { Link } from '../components/Link.js'
import { session, startRun } from '../session.js'
import { RunScreen } from './Run.js'

/**
 * `/q/<questionId>` — one question, untimed (F7, §7.2).
 *
 * The id alone regenerates the question *and* its four options in their original
 * order, which is what makes a link to a single question meaningful. A custom profile
 * has to arrive with the link (`?pf=`) or be known locally; if it is neither, the page
 * says so rather than quietly inventing a different question.
 */
export function QuestionScreen({ id }: { id: string }): JSX.Element {
  const started = useRef<string | null>(null)
  const parsed = parseId(id)
  const ready = profilesReady.value

  const profile = 'error' in parsed ? undefined : ready ? readProfile(parsed.profileRef, params()) : undefined

  useEffect(() => {
    if ('error' in parsed || !profile || started.current === id) return
    started.current = id
    const question = questionFromId(id, () => profile)
    if (isResolveFailure(question)) return
    startRun({
      // Untimed: a shared question is for examining, not for racing. Only the clock
      // and the count change, so the question keeps the id it was shared under.
      profile: practiceVariant({ ...profile, questionCount: 1 }, 'untimed'),
      mode: profile.defaultMode,
      seed: 0,
      practice: true,
      deck: { ids: [id], origin: 'single' },
      countdownMs: 0,
      navigateTo: null,
    })
  }, [id, profile])

  if ('error' in parsed) {
    return (
      <main class="page" data-testid="question-error">
        <p>That question id is not valid.</p>
        <Link to="/">Back to the start</Link>
      </main>
    )
  }

  if (!ready) {
    return (
      <main class="page" data-testid="question-loading">
        <p class="muted">Loading…</p>
      </main>
    )
  }

  if (!profile) {
    return (
      <main class="page" data-testid="question-unavailable">
        <p>Unavailable: this question was generated by a custom profile that was not included in the link.</p>
        <p class="qid">{id}</p>
        <Link to="/">Back to the start</Link>
      </main>
    )
  }

  if (session.value.phase === 'idle') {
    return (
      <main class="page" data-testid="question-loading">
        <p class="muted">Loading…</p>
      </main>
    )
  }

  return <RunScreen />
}
